"use client"
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import "./globals.css";
import { useState } from "react";
// import { Providers } from "@/store/provider";




// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {

  const [queryClient] = useState(() => new QueryClient());
  return (

    <html lang="en">
      
      <body
        className={`antialiased`}
      >
         {/* <Providers> */}
         <QueryClientProvider client={queryClient}>
        {children}
        </QueryClientProvider>
        {/* </Providers> */}
      </body>
    </html>

 
  );
}
